/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eightpuzzle.view;

import GameControler.Randomizer;
import javax.swing.JOptionPane;

/**
 *
 * @author icaro
 */
public class Principal extends javax.swing.JFrame {
    
    private GameWindow gw;
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }
    
    public void NewGame(){
        gw = new GameWindow();
        GameTabbedPane.removeAll();
        Randomizer.CreateString();
        Randomizer.CreateBoard(gw);
        GameTabbedPane.add(gw, "EightPuzzle Game Made by Icaro Daflon");
        GameTabbedPane.repaint();
    }
    
    public void exit(){
        System.exit(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        GameTabbedPane = new javax.swing.JTabbedPane();
        MenuBar = new javax.swing.JMenuBar();
        MenuFile = new javax.swing.JMenu();
        NewGameMI = new javax.swing.JMenuItem();
        RestartMI = new javax.swing.JMenuItem();
        ExitMI = new javax.swing.JMenuItem();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuFile.setText("File");

        NewGameMI.setText("New Game");
        NewGameMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewGameMIActionPerformed(evt);
            }
        });
        MenuFile.add(NewGameMI);

        RestartMI.setText("Restart Current Game");
        RestartMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestartMIActionPerformed(evt);
            }
        });
        MenuFile.add(RestartMI);

        ExitMI.setText("Exit");
        ExitMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitMIActionPerformed(evt);
            }
        });
        MenuFile.add(ExitMI);

        MenuBar.add(MenuFile);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GameTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GameTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RestartMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestartMIActionPerformed
        // Reinicia o jogo atual refazendo a grade
        GameTabbedPane.removeAll();
        Randomizer.CreateBoard(gw);
        GameTabbedPane.add(gw, "EightPuzzle Game Made by Icaro Daflon");
    }//GEN-LAST:event_RestartMIActionPerformed

    private void NewGameMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewGameMIActionPerformed
        // Inicia um novo jogo
        NewGame();
    }//GEN-LAST:event_NewGameMIActionPerformed

    private void ExitMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitMIActionPerformed
        // TODO add your handling code here:
        exit();
    }//GEN-LAST:event_ExitMIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ExitMI;
    private javax.swing.JTabbedPane GameTabbedPane;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu MenuFile;
    private javax.swing.JMenuItem NewGameMI;
    private javax.swing.JMenuItem RestartMI;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
